[treesearch]
num_draft_nodes = 3
debug_prob = 0.3
epsilon = 0.3
max_iterations = 10

[exec]
timeout = 3600
workspace = "./workspace"

[agent]
k_fold_validation = 1
data_preview = false

[agent.code]
model = "o5-mini"
model_temp = 1.0
